import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#565e74",
        primary: "#000000",
        "on-secondary-container": "#57657b",
        "on-primary-fixed": "#131b2e",
        background: "#f7f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        tertiary: "#000000",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#7c839b",
        "on-primary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e0e3e5",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-container": "#75859d",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "tertiary-container": "#0b1c30",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#b9c7e0",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        outline: "#76777d",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#d5e3fd",
        "surface-bright": "#f7f9fb",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d3e4fe",
        "on-surface-variant": "#45464d",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        surface: "#f7f9fb",
        "primary-container": "#131b2e",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#3a485c",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed": "#0d1c2f",
        "secondary-container": "#d5e3fd",
        secondary: "#515f74",
        "outline-variant": "#c6c6cd",
        success: "#1e7d34",
        "success-container": "#d3f5da",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        base: "4px",
        "2xl": "48px",
        xs: "4px",
        gutter: "16px",
        sm: "8px",
        lg: "24px",
        "container-padding": "32px",
        xl: "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
